### ISSUE TITLE
[Tool] Enable simple sensitivity analysis

### ISSUE THREAD

**Issue by FredericHirschmueller** [open-plan-tool/gui#14]
## Typical usecase

One project in which the user want to change a few parameters in the scenario and look how certain outputs of the scenario change as a fonction of the changing input.

### Required arguments
- fixed scenario parameters
- range of one input parameter to change (min, max and number of steps)
- wished output parameters
- value of the input parameter to change chosen for the reference scenario, there must be a reference scenario (if this value is different than the value of the existing scenario, then display an info box that a new scenario will be saved as reference scenario, one could also add -sensitivity analysis to the scenario name) 

### Where to provide the arguments ?

On step 4 of the scenario progression in a separate div

### Where can one access the sensitivity analysis ?

- From the result page (next to the Export results button) as link to step 4
- In infobox of Project

### Where would the user view the results ?

In the result page on the "Look at sensitivity analysis" tab 

### How/where would the user access the link to the sensitivity analysis ?
- from the step 4 after the status is done
- from the result page

**Comment by FredericHirschmueller** [comment]
You mean an asset parameter like specific costs, om costs or asset lifetime? These parameters and other input parameters of an asset could be part of a sensitivity analysis.

**Comment by Bachibouzouk** [comment]
Yes this is what I meant, thank you :)

**Comment by Bachibouzouk** [comment]
If I choose a variable parameter which is located in many assets (like feedin_tariff for DSOs), do we want to give the option to set the variable value for all the assets in the sensitivity analysis or we just ask the user to choose which asset's should see one of its parameters vary?

**Comment by FredericHirschmueller** [comment]
Normally you only change one parameter in a sensitivity analysis. But I think it would be nice if we give the user to option to change this specific parameter also for other assets. This gives the user more freedom of choice and could make the handling easier.
