### ISSUE TITLE
[Tool] In single scenario result view a graph should always update to currently selected scenario

### ISSUE THREAD

**Issue by FredericHirschmueller** [open-plan-tool/gui#153]
If I create a graph for one scenario in the single scenarios result view this graph is also shown in all the other scenarios with the values of the scenario in which I created the graph. I think it would be good to have this created graph in the other scenarios as well, but with the values of that specific scenario. I think we shouldn't mix the values of different scnearios in the single scenario view. This feature should be implemeneted for the compare scenarios view.

**Comment by Bachibouzouk** [comment]
There might be a problem with this : if one scenario (A) has an asset another scenario (B) does not have, then there will be an error when trying to load data from an unexisting asset

**Comment by Bachibouzouk** [comment]
It was concluded with @FredericHirschmueller that this should not be implemented
