### ISSUE TITLE
[Tool] Changing the efficiency of the battery from 1,0 to 0,95 causes big differences in the results

### ISSUE THREAD

**Issue by FredericHirschmueller** [open-plan-tool/gui#156]
For the scenario 4 of the Industriestandort usecase the results change a lot when I change the efficiency of the battery from 1,0 to 0,95. The optimized capacity of the battery in the first case results in 8379 kWh and in the second case in 1799 kWh. Is this reasonable?

**Comment by Bachibouzouk** [comment]
One should test that again as the MVS changed
