### ISSUE TITLE
The Constraints are not working in MVS

### ISSUE THREAD

**Issue by mstich0** [open-plan-tool/gui#161]
@c-moeller

**Comment by Bachibouzouk** [comment]
Can you be a bit more specific @mstich0, @c-moeller  ? Can you also provide the steps you follow so that the constraints are not working? If the problem is MVS, then it should rather be an issue in the MVS repository

**Comment by mstich0** [comment]
@Bachibouzouk: When having an easy model set sup eg. grid, wind-power-station batterysystem and demand and setting the constraints for min EEG (Kleinster Anteil Erneuerbarer Energien (factor)) or min autarky, the optimization ignores the constraints.

probably it is an MVS bug then, im not sure how to change the labling...

**Comment by Bachibouzouk** [comment]
Did you try to tick the option "run with the LP file" before clicking on runsimulation (if you do so, please shorten the simulation time in the settings to 3 days, no need to have a year of timeseries to check the LP file ;))
