### ISSUE TITLE
[Bug] Server Error after creating a new scenario

### ISSUE THREAD

**Issue by FredericHirschmueller** [open-plan-tool/gui#167]
When I try to create a new scenario I always get a server error. I tried to create a new scenario with a new project and an existing project and I always got the server error.

**Comment by Bachibouzouk** [comment]
This was due to the addition of "Go to simulation" link in the footer. If the scenario isn't created yet one cannot go to its step 4 (a scenario is created after the user clicked next in the first step of the scenario creation steps.
