### ISSUE TITLE
efficency for heat pumps

### ISSUE THREAD

**Issue by mstich0** [open-plan-tool/gui#173]
When using the heat pump component one wants to insert a coefficient of performance (COP) instead of a efficency. It works basically same as the efficency, but is not limited to values between 0-1 but can have values above 1. Values above 1 are however currently not allowed for the effiency which makes it impossible to use the heat pump component.

**Comment by Bachibouzouk** [comment]
It is now possible in the dev server (you can play with the input values, but then I haven't checked yet how those can be recieved by MVS, so you cannot yet proceed to simulation)

**Comment by Bachibouzouk** [comment]
It was decided with @c-moeller  to use [oemof-thermal](https://github.com/oemof/oemof-thermal/blob/1d12419c7500ad74742e433f94f5cfe8f6abd787/src/oemof/thermal/compression_heatpumps_and_chillers.py#L17) to compute the COP from temperature.

This means the user should be able to input the COP manually if they want, or click on a button and being prompt to provide the temperature timeseries or scalar value.

We could open a new window(https://stackoverflow.com/questions/19528173/bootstrap-open-another-modal-in-modal) but multiple modals are not supported to it would be a hassle to save the other values of the form to display them when returning to the form after closing the new window.

Easier is to toggle some div in the existing form when clicking on the button

**Comment by Bachibouzouk** [comment]
```
temp_high : list or pandas.Series of numerical values
        Temperature of the high temperature reservoir in :math:`^\circ C`
    temp_low : list or pandas.Series of numerical values
        Temperature of the low temperature reservoir in :math:`^\circ C`
    quality_grade : numerical value
        Factor that scales down the efficiency of the real heat pump
        (or chiller) process from the ideal process (Carnot efficiency), where
         a factor of 1 means teh real process is equal to the ideal one.
    factor_icing: numerical value
        Sets the relative COP drop caused by icing, where 1 stands for no
        efficiency-drop.
    mode : string
        Two possible modes: "heat_pump" or "chiller" (default 'None')
    t_threshold:
        Temperature in :math:`^\circ C` below which icing at heat exchanger
        occurs (default 2)
```

**Comment by Bachibouzouk** [comment]
Currently on the development server the heat_pump accepts COP and perform the conversion towards efficiencies
