### ISSUE TITLE
components needed for usecases (not available yet)

### ISSUE THREAD

**Issue by mstich0** [open-plan-tool/gui#175]
I´m not sure if these components/parameters are aleady implemented in MVS or not but I would consider those to be crucial for project applications and they are not available in the open_plan tool yet:

o thermal storage input parameters for:
-losses relative to total capacity (add)
-SOC min/max (remove)

o CHP component with fixed ratio between heat/electricity (back_pressure=True) ( label='back_pressure_turbine')

o CHP component with variable ratio between heat/electricity: (back_pressure=false), (label='combined_cycle_extraction_turbine'), could be called 

o heat pump component needs a COP instead of a efficency input (and it has to be allowed to be greater than 1 !!!),
also the possiblility to add a timeseries COP instead of a single value would be quite useful

o a new "grid component" to act as a heat network (quite reduced complexity but already very usefull). Could be designed out of a storage component with little capacity (only as much as needed to make it work) but with the possibility to set the input and output capacity (which should be the parameter that is also possible to get optimized by investment)

o the option to load a price chart in €/kWh at any given timestep into the electric grid component to include effect of actual electrity prices for energy suppliers (not only end consumers)

**Comment by Bachibouzouk** [comment]
@mstich0 - can you open a separate issue for the "grid component" ? The rest of the list was closed in #183
