### ISSUE TITLE
Heatpump with two inputs -> 1 COP instead of 2 efficencies

### ISSUE THREAD

**Issue by mstich0** [open-plan-tool/gui#180]
Concerning the heatpump component which has two inputs (one for electricity / one for low temperature heat):

Right now the component is set up with two efficiencies in "efficiency 1"- field so if I want to have a COP of 4 I need no set it as [0.25, 0.75]. 
It would be great if we would **only have 1 value-input for efficiency (or better the COP!)** and out of that calculate the two conversion factors.

Would it be possible to do the calculation inside the component? 
So for COP=4 as input calculating:
=[1/COP , (COP-1)/COP]  
=[1/4 , (4-1)/4]
=[0.25, 0.75]

**Comment by Bachibouzouk** [comment]
We would then only need to provide 2 efficiencies for CHP then, right?

**Comment by mstich0** [comment]
yes for the fix chp we would still need two efficiencies.

**Comment by Bachibouzouk** [comment]
This should now work on the development server
