### ISSUE TITLE
Bug in sankey-diagram for heatpump component

### ISSUE THREAD

**Issue by mstich0** [open-plan-tool/gui#181]
When using the new heatpump component (with el and heat input) the sankey diagram is not getting created correctly.  The input flows seem to not be calculated with the corresponing input-conversion factor, but instead they have the size of the output-flow.

**Comment by Bachibouzouk** [comment]
One needed to multiply the outputflow of the heat_pump by the efficiencies to get the input flows

**Comment by Bachibouzouk** [comment]
This should be fixed in the development server
