### ISSUE TITLE
Secondary output for new CHP-component not visible

### ISSUE THREAD

**Issue by mstich0** [open-plan-tool/gui#182]
The secondary output flow (heat-output) of the CHP component is not shown in the corresponding result-diagrams, only the primary output (el-output) is shown.

**Comment by Bachibouzouk** [comment]
This needs to be changed in the function `dashboards.models.available_timeseries` as well as in MVS

**Comment by mstich0** [comment]
There is actually a similar issue for the heatpump component. There are **two inputs** for it but currently only the heatinput will be shown in the results. The electrical input is not shown, only the grid-component output (it is the same size only if there is just these two components connected to the el_bus).

**Comment by Bachibouzouk** [comment]
I guess it might be a matter of convention if you consider a heat pump as an electrical asset or a heat asset or both, I would tend to consider it both, but maybe for lcoe calculation it does not make sense?

**Comment by mstich0** [comment]
As both forms of energy are relevant in this component I would agree to label it to both assets. Concerning the LCOE calculation I dont see a problem as both inputs would be used for calculation of the LCOE of the product heat. As there is no product electricity this should not be a problem.

**Comment by Bachibouzouk** [comment]
@mstich0 - can you see if this issue is still open and close it with mention to #204?

**Comment by Bachibouzouk** [comment]
Closed in #204
