### ISSUE TITLE
[Tool] Implement the possibility to install the tool locally

### ISSUE THREAD

**Issue by FredericHirschmueller** [open-plan-tool/gui#20]
It would be nice, to download the tool, so it can be run locally on a computer. This is especially interesting for companies, who are concerned about their data.

**Comment by Bachibouzouk** [comment]
This is possible already, this issue can be closed when the repository is made public

**Comment by FredericHirschmueller** [comment]
I thought this repository is already public?

**Comment by Bachibouzouk** [comment]
Yes you are right, what I meant is that there is no code uploaded yet and publicly visible

**Comment by Bachibouzouk** [comment]
The code is uploaded publicly now, so I will close this issue
