### ISSUE TITLE
nominal power of heatpumps

### ISSUE THREAD

**Issue by mstich0** [open-plan-tool/gui#201]
Currently the (thermal) **output** of a heatpump is set up to be optimzed in the investment. 
We should change that to the **electricity in-flow** as this is the "real" cost parameter per capacity.

Right now a heatpump with an optimzed capacity can produce a constant amount of heat no matter of the (changing) COP/temperature. In reality the output should be proportional with the (changing) COP.

so the solph.Investment(...) should be moved from **outputs** the **el-input**. This is for any heatpumnp the case, (but not for any transformer)

**Comment by Bachibouzouk** [comment]
This has to be changed in MVS, I will tackle this

**Comment by Bachibouzouk** [comment]
Could you send me a use case for it? Then we could chat on skype about it

**Comment by mstich0** [comment]
Currently not working as intended. It seems the investment is not saved/recognised for the component, in the results it show the inout and output correctly but the investment is said to be 0
