### ISSUE TITLE
storage bug

### ISSUE THREAD

**Issue by mstich0** [open-plan-tool/gui#202]
When working with the storage component there is showing a strange bug from time to time which I found hard to reproduce. Over a period of a year it only happens in 3 single timesteps. 

The input and output of the storage rise at the same time for a very high amount. Neither reducing the efficiency nor adding dispatch costs to the component would stop this happening.

As it leads to rather strange results I would consider it as quite a problem. Is it possible that this might result from an unfinished optimization? It seems to happen only in longer simulations.

![Image](https://user-images.githubusercontent.com/105202247/199289259-79ac15c8-ba2c-4e69-8176-e93336cebd23.png)

**Comment by Bachibouzouk** [comment]
https://forum.openmod.org/t/prevent-electrical-storage-from-charging-discharging-at-the-same-time/1785

**Comment by Bachibouzouk** [comment]
How often did you see this happen?

**Comment by mstich0** [comment]
When working on the central-heat-network uscase it happened consistently  (also on the same timesteps), while in other cases it does not. Changing parameters/costs would lead to more or fewer of these spikes. As in the Link described this would be a "reasonable" behaviour if there was too much heat and no sink, but in our cases there is always a sink in the bus which would be cheaper to use. As we dont want to create a MILP out of it it seems to be an issue in oemof.
I´d suggest to give an option to set the charging and decharging capacity as ratio of the storage capacity (I think currently it is always 1). Especially for batteries this is a relevant input parameter anyway, which we should offer. For the heat storage I could set it to a reasonable value which might be 1/1000 and smaller for big tanks and therfore the spikes would at least not "ruin" the plot

**Comment by Bachibouzouk** [comment]
The dispatch price does not get passed correctly to the MVS, it will be set to the output bus of the storage

**Comment by Bachibouzouk** [comment]
Closed by #206
