### ISSUE TITLE
Apply peak demand price on consumption and feed-in

### ISSUE THREAD

**Issue by mstich0** [open-plan-tool/gui#208]
Currently the **peak demand price** in the supplier component is only active for **consumption** and is ignored by **feed-in**. This is not accurate, it would make sense to link those two investments so that the maximum output flow is equal to the maximum input flow. 

This should be possible with oemof.solph.constraints.equate_variables() with still keeping it LP:

oemof.solph.constraints.equate_variables(
om.InvestmentFlowBlock.invest[bus_el, grid]
om.InvestmentFlowBlock.invest[grid, bus_el]
)

the **peak demand price** should therfore be only 0.5 of the input value as it is applied two times (for both flows)

**Comment by FredericHirschmueller** [comment]
@mstich0 is this issue solved, so can we close it?
