### ISSUE TITLE
Server bugs

### ISSUE THREAD

**Issue by b-skorka** [open-plan-tool/gui#245]
There are some bugs I run into using open-plan:
•	Creating a new scenario in a project runs in Server Error (500)
•	Reset simulation after you have run a simulation ends in 403 Forbidden and doesn’t reset the simulation
•	After you have run a Simulation, a click on Sensitivitätsanalyse runs in Server Error (500)
I have tried it in Firefox and Edge, both have the same errors

**Comment by Bachibouzouk** [comment]
Thank you for submitting an issue, I will look into it
