### ISSUE TITLE
[Data import] It should be possible to run a simulation by providing a single .xlsx file

### ISSUE THREAD

**Issue by FredericHirschmueller** [open-plan-tool/gui#36]
**Bachibouzouk commented on 20 Jan**

This format is unfortunately very popular so we have to abide by popularity. One could use the MVS csv structure and place informations in different tabs of the file, where the tabs have very specific names (like the name of the csv files in csv_elements or in time_series

**c-moeller commented on 21 Jan**

What about the option of providing a template (or several templates) which you can download and which the user should use to fill their data in the given lines and columns?

**Bachibouzouk commented on 21 Jan**

It is a nice way of having the tabs labelled correctly :)

**Comment by Bachibouzouk** [comment]
As we now have the possibility to import/export as json file and load usecases directly from the tool, I will close this issue. As people can simply drag and drop their component and build a system, there is no need to build the system from an excel file
