### ISSUE TITLE
[Tool] Enable to save a grid model of a scenario although not all components are fully parameterized

### ISSUE THREAD

**Issue by FredericHirschmueller** [open-plan-tool/gui#37]
Currently it is not possible to close the parameter mask when not all the input parameters are filled out. 

Suggestion: when closing the parameter mask an info box opens with a note that not everything has been filled out. 

Option: close anyway. Then this component is marked with a red exclamation mark. After filling out all parameters correctly the component is marked with a green check mark.

**Comment by Bachibouzouk** [comment]
The problem we are facing here is the database: clicking on "save" in the parameter mask save the parameter values in the database. The database is picky, one cannot not provide the value of one or more parameters if they were not previously flagged as not required or if there are required but have a default value. If a component is not saved in the database, it will disappear once the page is refreshed.

A solution might be to provide default values for all components

**Comment by Bachibouzouk** [comment]
Suppose you close your browser and you come back then to your energy model, then components that you will see are only the ones that are saved in the database (they are fetched from it and then rendered so we can see them). One could either make the appearance of a newly dragged component in the database different so that the user must click on it and save it, or automatically save it in the database (but this requires default values)

**Comment by FredericHirschmueller** [comment]
Since we wanted to provide default values for every component, this might be a nice solution anyways.

However, I think this issue is already solved, because currently it is possible to save a grid model, even though not all components are fully parametrized. I would only get an error when I try to run the simulation, right?

**Comment by Bachibouzouk** [comment]
https://github.com/open-plan-tool/gui/blob/main/app/static/assettypes_list.csv
@c-moeller add a column to an existing csv file with the default values in the same order as in the `asset_fields` columns
