### ISSUE TITLE
[Tool] Optimized capacities are not being displayed although production time series is non-zero

### ISSUE THREAD

**Issue by minhki95** [open-plan-tool/gui#4]
Seen in scenario of @FredericHirschmueller. Please provide the scenario data, so we can fix it.

**Comment by minhki95** [comment]
This is kind of outdated because the results page is being restructured. Still might be relevant if this will remain as a default graphic in the results page

**Comment by FredericHirschmueller** [comment]
Sorry, I've just seen my linkage. I think this was not related to a specific scenario but more a general comment for the result page. I think we included the optimized capacities of a simulation into the structure of the new result page.

**Comment by minhki95** [comment]
Okay I fixed the bug in the branch feature/capacity_graph #103 for both the default plot and the customizable plot.
