### ISSUE TITLE
[Bug] For the "Net zero energy system" constraint no numbers can be entered as a value

### ISSUE THREAD

**Issue by FredericHirschmueller** [open-plan-tool/gui#50]
To enter a value for this constraint the drop-down list is available to choose between "Choose", "Yes" and "No".

**Comment by Bachibouzouk** [comment]
This is because the constraint is make a net zero energy system or not, it is a boolean (a yes/no question)

**Comment by FredericHirschmueller** [comment]
That makes sense. This would mean that we also don't need the value input box. The constraint must be only activated or disabled.

![Unbenannt](https://user-images.githubusercontent.com/70587431/148033839-96c15736-cc40-4b9c-abd1-a112e2758796.PNG)
