### ISSUE TITLE
[Tool] Export the lp-file

### ISSUE THREAD

**Issue by FredericHirschmueller** [open-plan-tool/gui#62]

**Comment by Bachibouzouk** [comment]
This is possible on https://mvs-open-plan.rl-institut.de/ (this will be out simulation server for open_plan, so we don't mess up with epa-eland and can benefit from improved https://github.com/rl-institut/multi-vector-simulator versions.
Right now mvs release [1.0.1rc2](https://pypi.org/project/multi-vector-simulator/1.0.1rc2/) is based on https://github.com/rl-institut/multi-vector-simulator/tree/feature/save-lp-file-on-server. I will soon make a PR where is it possible to ask to get the lp file

**Comment by Bachibouzouk** [comment]
One question is: where in the online tool should the user choose to have the LP file (it is for advanced users)?

Possible suggestions:
- set it in user parameters
- set it in scenario parameter (adding it in the database model)
- set it on the last scenario creation's step with a checkbox (how I'll implement it in the first time)

As it is for advanced users I think it is good that you don't see this option by default

**Comment by Bachibouzouk** [comment]
@c-moeller - what do you think?
