### ISSUE TITLE
[Tool] Implement the possibility to install the tool locally

### ISSUE THREAD

**Issue by FredericHirschmueller** [open-plan-tool/gui#85]
Due date 2022-07-31

It would be nice, to download the tool, so it can be run locally on a computer. This is especially interesting for companies, who are concerned about their data.

**Comment by Bachibouzouk** [comment]
I re-open this issue until @FredericHirschmueller can install the tool locally successfully!

**Comment by Bachibouzouk** [comment]
https://docs.docker.com/desktop/windows/install/

**Comment by Bachibouzouk** [comment]
@c-moeller , @FredericHirschmueller - I added the description to deploy the webapp and simulation server locally

**Comment by Bachibouzouk** [comment]
@FredericHirschmueller - I improved the local installation steps in #170, you can try to follow the [updated readme](https://github.com/open-plan-tool/gui/tree/fix/docker-deploy#deploy-using-docker-compose) steps (you just need to do `git checkout fix/docker-deploy` after cloning the repository in a new folder). 

You might also need to tear the existing docker containers down (press stop in your docker container list in the docker dashboard (which you access by clicking on the little whale in your "running programs" task bar in the lower right part of your computer screen))

**Comment by Bachibouzouk** [comment]
I installed docker desktop on windows 10 and I could then deploy the app without trouble
