### ISSUE TITLE
[Tool] The result button of a scenario should lead to the results of that specific scenario and not the general result page

### ISSUE THREAD

**Issue by FredericHirschmueller** [open-plan-tool/gui#87]
After clicking on the result button of a specific scenario in the project overview, the result page is displayed showing the results of the first project in the result view. When clicking on the result button of a specific scneario the result page of that specific scenario should be displayed.

**Comment by Bachibouzouk** [comment]
We have several usecases:
- click on the general "Results" button from the navbar at the top --> cannot know the project selected, take first one as default, cannot know the scenario selected, take first one (if any) as default
- click on the Result button of a project --> the project dropdown should be preselected to the choosen project, cannot know the scenario selected, take first one (if any) as default
- click on the Result button of a scenario -->  the project dropdown should be preselected to the choosen project, scenario should be selected by default
- click on "show results" from step 4 of scenario creation ->  the project dropdown should be preselected to the choosen project, scenario should be selected by default

**Comment by Bachibouzouk** [comment]
Right now it will always be the 1st project which is selected

**Comment by FredericHirschmueller** [comment]
I like your suggestions for all 4 usecases :)

**Comment by Bachibouzouk** [comment]
Only the project selection in the dropdown does not update the page adequately now (on the PR)
