### ISSUE TITLE
[Bug] Some input parameters are not saved when downloading a scenario and upload it again

### ISSUE THREAD

**Issue by FredericHirschmueller** [open-plan-tool/gui#94]
When a scenario is downloaded as a file and uploaded again some of the input parameters are not saved and have to be entered again. So far I recognised two input parameter:

- [ ]  pv plant / wind turbine: renewable asset (choose/yes/no)

- [ ]  the generation timeseries of the assets is not saved, even though the demand timeseries is saved

**Comment by Bachibouzouk** [comment]
This was linked to the asset field being referenced with a space in the name of the asset field for these specific two asset fields (https://github.com/isichos/epa/pull/1).
