### ISSUE TITLE
[Bug] After running a simulation the status does not change to "DONE" and the results are not accessible 

### ISSUE THREAD

**Issue by FredericHirschmueller** [open-plan-tool/gui#95]
After clicking on the "run simualtion" button an other button appears to check the status. This button leads to an other page where the JSON file is displayed and the status is shown on this page.

1. Even when the status in the JSON file shows "DONE" the simulation page doesn't change to "DONE" and the result page is not accessible.

2. When one clicks on the "check status" button it would be better to stay at this page and not display the JSON file, because this might be confusing. It would be better to just refresh the simulation page and update the status. When status changes to "DONE" a button to the result page should appear that leads to the result page.

**Comment by Bachibouzouk** [comment]
Issue duplicate with #34 :)
